language: node_js

env:
  - TEST_NODE=yes
  - TEST_PYTHON=no

matrix:
  include:
    - python: 2.7
      env:
        - TEST_NODE=no
        - TEST_PYTHON=yes
    - python: 3.4
      env:
        - TEST_NODE=no
        - TEST_PYTHON=yes
    - python: 3.5
      env:
        - TEST_NODE=no
        - TEST_PYTHON=yes
    - python: 3.6
      env:
        - TEST_NODE=no
        - TEST_PYTHON=yes

before_install:
  - curl -OL https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
  - unzip protoc-3.2.0-linux-x86_64.zip -d protoc3
  - sudo mv protoc3/bin/* /usr/local/bin/
  - sudo mv protoc3/include/* /usr/local/include/
  - if [ $TEST_NODE == "yes" ]; then cd js; npm run prepare; fi
  - if [ $TEST_PYTHON == "yes" ]; then cd python; fi

install:
  - if [ $TEST_NODE == "yes" ]; then npm install; fi
  - if [ $TEST_PYTHON == "yes" ]; then pip install protobuf==3.3.0; fi

script:
  - if [ $TEST_NODE == "yes" ]; then npm test; fi
  - if [ $TEST_PYTHON == "yes" ]; then python setup.py test; fi
